Friendships v2
AhmedTohamy01/Social-Network pull request #3
Opened 2020-10-28 20:14 UTC by ezeilo-su

Every detail that will be helpful in reviewing this project is found in the README section.

2020-10-28 20:41 UTC, maelfosso requested changes
# Changes required 🔴 

Hello,

Thank you for the job done so far
However, there are some issues that need to be solved

1- Your `rubocop.yml` is not identical to the required one and it looks like the Github Action workflow is not enable. Kindly follow this [link](https://github.com/microverseinc/linters-config/tree/master/ror) to know how to fix those issues

2- Running `rspec` gives me this error
```rb
) UsersIndices index page without friend requests or pending friends should have a button to add each friend
     Failure/Error: expect(page).to have_button('Add Friend', count: 30)
       expected to find visible button "Add Friend" that is not disabled 30 times, found 29 matches: "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
     # ./spec/features/users_index_spec.rb:36:in `block (4 levels) in <main>'

Finished in 2 minutes 53 seconds (files took 5.08 seconds to load)
```

3- Concerning unit testings, kindly remove the unused files, please

4- Here is what I obtain after accepting a friendship request
```rb
2.7.0 :001 > Friendship.all
  Friendship Load (0.7ms)  SELECT "friendships".* FROM "friendships" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friendship id: 1, user_id: 2, friend_id: 1, confirmed: true, created_at: "2020-10-28 20:28:27", updated_at: "2020-10-28 20:31:17">]> 
2.7.0 :002 > 
```
You will notice that there is only one line. 
The main and only goal of this milestone is, when friendship is confirmed, create an additional row with reversed user-friend pair.

Kindly implements it, please.

5- Read the comments left below

Kindly make the suggested changes and once done, submit a new code review request
Thanks

Mael FOSSO

2020-10-28 20:41 UTC, maelfosso commented on app/views/users/show.html.erb
> +    <% end %>
Kindly remove logic from views, please. Implement them in view helpers

2020-10-28 20:41 UTC, maelfosso commented on app/views/users/index.html.erb
> +          <% end %>
Kindly remove logic from views, please. Implement them in view helpers

2020-10-28 20:41 UTC, maelfosso commented on app/views/posts/_post.html.erb
>      <% end %>
Kindly remove logic from views, please. Implement them in view helpers

2020-10-28 20:41 UTC, maelfosso commented on app/models/user.rb
> +  has_many :friend_requests, -> { merge(Friendship.pending) }, through: :inverse_friendships, source: :user
These requests can help you.

```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

2020-10-28 20:41 UTC, maelfosso commented on app/models/post.rb
> +  # scope :ordered_by_most_recent, -> { order(created_at: :desc) }
Kindly remove comments

2020-10-28 20:41 UTC, maelfosso commented on app/models/friendship.rb
> +  # default_scope -> { order(created_at: :desc) }
Kindly remove comments

2020-10-28 20:41 UTC, maelfosso commented on app/controllers/posts_controller.rb
> +                                 friends_ids, current_user.id).paginate(page: params[:page])
**OPTIONAL**
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

2020-10-29 21:58 UTC, kevincappuccino requested changes
# [STATUS] INVALID PULL REQUEST 🛑

### Sorry team, TSE's can't review invalid pull requests, please, to get your project approved, you guys have to solve the following:

- [ ] This is must be a re-review of the firendship-2, but you accidentally asked for a review of the Deploy milestone, thats why I can't review it now. 

## As always, I wish you all the very best and see you both at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)


<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In the real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-11-01 23:36 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Lets implement linter checks  
- [ ] Let's write a unit test for all components
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-11-02 22:27 UTC, blackpintz requested changes
# Status: Changes Required

**Hello team. Great job implementing the changes. However, there are a few more fixes needed.**

1). **Please write unit tests for the following files in `app/models` folder -` comment.rb`, `like.rb`, `post.rb`.**
2). **Please write unit tests for your controllers and helpers as well.**
3). **Remove comments in files in the helpers folder. Check comment below for one example.**


## Optional

1). **You can add in your readme, instructions on how to run tests for your project.**

### Happy coding 😃.

**PS: You can reach me on slack(Rose Wanjohi).**

2020-11-02 22:27 UTC, blackpintz commented on app/helpers/application_helper.rb
> +  # Returns true if the user is logged in, false otherwise.
Remove the comments on line 2 and 12. Remember to check the other files especially in this folder.

2020-11-02 22:27 UTC, blackpintz commented on app/models/post.rb
>  end
There are no unit tests for this file.

2020-11-03 10:02 UTC, rOluochKe approved these changes
Hello Team,
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-11-03 10:23 UTC, ezeilo-su commented
Thanks, all, who contributed to the success  of this project. Thanks for all your support!

2020-11-03 10:23 UTC, closed without merging